baseurl = "https://ogfonline.org/"  # Include trailing slash
languageCode = "en-us"
title = "Oromo Global Forum"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

enableInlineShortcodes = true

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "News"
  URL = "news"
  weight = 2
  
  [[menu.main]]
  name = "Resource Center"
  URL = "resource"
  weight = 3

  [[menu.main]]
  name = "Advocacy"
  URL = "advocacy"
  weight = 4

  [[menu.main]]
  name = "Events"
  URL = "events"
  weight = 5

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 6

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.footer]]
  name = "News"
  URL = "news"
  weight = 2
  
  [[menu.footer]]
  name = "Resource Center"
  URL = "resource"
  weight = 3

  [[menu.footer]]
  name = "Advocacy"
  URL = "advocacy"
  weight = 4

  [[menu.footer]]
  name = "Events"
  URL = "events"
  weight = 5

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 6


#################### default parameters ################################
[params]
logo = "images/logo_2.png"
home = "Home"
# Meta data
description = "Online magazine on Oromo affairs"
#author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "UA-174948137-1"
# Contact Information
#mobile = "916-234-5555"
email = "oromiaglobalforum@gmail.com"
location = "USA"
# copyright
copyright = "| copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
#[params.newsletter]
#enable true
#title = "Join Our Newsletter"
#content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/OromiaGlobalForum"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/OromiaGlobal"

#[[params.social]]
#title = "instagram"
#icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "github"
#icon = "ti-github" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"

# If you want to use disqus, uncomment the line below
disqusShortname = "ogfonline-org.disqus.com"

[deployment]

[[deployment.targets]]
name = "ogfonline.org"
URL = "s3://ogfonline.org?region=us-east-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID =	"E3LKQC9N41JD7V"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
